info:
  _postman_id: 73090675-1263-4e22-9013-ca78aa97413f
  name: New Collection
  schema: https://schema.getpostman.com/json/collection/v2.0.0/collection.json
item:
  - name: Burgers
    item:
      - name: get burgers
        protocolProfileBehavior:
          disableBodyPruning: true
        request:
          method: GET
          header: []
          body:
            mode: raw
            raw: |-
              {
                 "name": "Abdi", 
                    "burger": "Mr.Beast Burger",
                    "flavor": "Kechup",
                    "remove": "onions"
              }
            options:
              raw:
                language: json
          url: '{{DEV_URL_BURGERS}}'
        response: []
      - name: Update Burger
        request:
          method: PUT
          header:
            - key: Authorization
              value: Brearer {{BurgerToken}}
              type: text
          body:
            mode: raw
            raw: |-
              {
                 "name": "Abdi", 
                    "burger": "Mr.Beast Burger",
                    "flavor": "Kechup, Mustard",
                    "remove": "onions, tomatoes"
              }
            options:
              raw:
                language: json
          url:
            raw: '{{DEV_URL_BURGERS}}/:id'
            host:
              - '{{DEV_URL_BURGERS}}'
            path:
              - ':id'
            variable:
              - key: id
                value: |
                  f2eba945-19d7-48c9-8d60-afe454ab1529
        response: []
      - name: Delete Burger
        request:
          method: DELETE
          header:
            - key: Authorization
              value: Brearer {{BurgerToken}}
              type: text
          url:
            raw: '{{DEV_URL_BURGERS}}/:id'
            host:
              - '{{DEV_URL_BURGERS}}'
            path:
              - ':id'
            variable:
              - key: id
                value: 8ca1a1c3-7363-44f0-be72-f08becf31bfd
        response: []
      - name: Create Burger
        request:
          method: POST
          header: []
          body:
            mode: raw
            raw: |-
              {
                 "name": "Abdi", 
                    "burger": "Mr.Beast Burger",
                    "flavor": "Kechup",
                    "remove": "onions"
              }
            options:
              raw:
                language: json
          url: '{{DEV_URL_BURGERS}}'
        response: []
      - name: Get One Burger
        request:
          method: GET
          header:
            - key: Authorization
              value: Brearer {{BurgerToken}}
              type: text
          url:
            raw: '{{DEV_URL_BURGERS}}/:id'
            host:
              - '{{DEV_URL_BURGERS}}'
            path:
              - ':id'
            variable:
              - key: id
                value: |
                  468d1de3-ff82-4c97-8c86-cd8f5a3d6016
        response: []
  - name: register user
    request:
      method: POST
      header: []
      body:
        mode: raw
        raw: |-
          {
              "name": "Aubrey",
              "email": "Aubrey5@email.com",
              "password": "password",
              "description": "I want My Burger without tomato"
          }
        options:
          raw:
            language: json
      url: '{{DEV_URL_AUTH}}/register'
    response: []
  - name: login
    event:
      - listen: test
        script:
          exec:
            - const jsonData = pm.response.json()
            - pm.globals.set("BurgerToken", jsonData.token)
          type: text/javascript
    request:
      method: POST
      header: []
      body:
        mode: raw
        raw: |-
          {
             "email": "Aubrey5@email.com",
              "password": "password"
          }
        options:
          raw:
            language: json
      url: '{{DEV_URL_AUTH}}/login'
    response: []